default:
  participant_data_file: "data/fit_count_recorders.csv"
  data_file: "data/fit_count.csv"
  computation_script_bg: "computations/computations_poms.R"
  computation_script_user: "computations/computations_poms.R"
  default_template_file: "templates/poms.Rmd"
  template_html_file: "templates_html/poms_template.html"
  pandoc_path: "C:/Program Files/RStudio/resources/app/bin/quarto/bin/tools"